name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution calendar
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Im-1ucky
          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Generate GitHub numbers
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.numbers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Im-1ucky

          base: header, activity, community, repositories, metadata

          repositories: 100
          repositories_forks: no

      - name: Generate most used languages
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Im-1ucky

          base: ""

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
